### ISSUE TITLE
Feature: Use different Markers per ZOO Category

### ISSUE THREAD

**Issue by marcorensch** [rvalitov/widgetkit-map-ex#17]
@rvalitov :
As i can see there is acutally no Way (or Guide) to use it with **Content Type ZOO Category** and assign a custom icon for each category or Type, is that right?

**Comment by rvalitov** [comment]
I haven't tested it with ZOO. So, probably it's not supported yet. If you want this feature to be implemented in the future releases of the widget, then please provide some screenshots (if possible) of what you want and expect from the widget, or some more comments. This will help me to understand better your idea and request.

**Comment by rvalitov** [comment]
Thank you for sharing your research how to use the MapEx widget with ZOO!
The Wiki is updated with related article ["Using MapEx with ZOO"](https://github.com/rvalitov/widgetkit-map-ex/wiki/Using-MapEx-with-ZOO).

**Comment by marcorensch** [comment]
Hi i have no idea if you can reopen this feature Request here? because my Guide is to Edit Map Marker per Single ZOO Item. :-)

I have done some "researches" and now i think there exist two possibilities to implement ZOO as good as possible. There are just ideas i don't know if you are interested or not - for me i have my hardcoded Version its a bit strange but it works :-P.
Here my Ideas:

**First possibility:**
All changes can be done in MapEx Widget (Settings Screen)
Tasks would be:
- get Categories Informations per Item
- get Type Information per Item
- get Type Information per App (Backend Usage)*
- Create backend Interface to change Icon per (Type / Category)

As example with
Widget Mode = Types (=Take all items of Type XY of this App across all categories)
with 
`'categories'   => $item['categories']`
you are able to catch the categories per Item then it should be possible to setup the PIN Marker Icon on a new Layer:
1. Default Icon (nothing set) --> as exist
2. MapEx Custom (MapEx General Setting) --> as exist
3. Category Setting (new Setup Option in MapEX Widget) --> New
4. Item Setting for Marker --> As exist already in your Code (My Guide)

Otherwise its also possible to turn that totaly, that means:
If selected: Mode = Categories (= Take all items of Category A across all Item Types)
And then the user can define an Icon for each Item Type (*Additional Task: get Type Informations for selected App)

My Problem: i have TOTALY no clue how to select the Array Elements with the Category Name...
and tell then, "hey, if you have Category A change PIN Value to: a.png". 

**Second Possibility (could be the easier one but i can't get a finished solution in my mind)**
the tasks would be:
- Create an Element for MapEx to define the Icon Marker Image
- Add the ability that MapEx uses ZOO's Render Feature

I have already tried to setup the icon with the creation of a custom Text Element (and it worked!). The Problem is, to set the Value for each Item of this Type... To have the possibility to do it on just One Place you have to fix it in the ZOO App Element Settings Screen. If you then create a new item for this type the Value is set and everyone is happy. But if you change the Value after you have created your items you have to reopen and save every item again to update the Value in the Field for this item. so if there exist a possibility to create a Magic _if Value changed update it for all App Type Items with this field_ - Button this solution could be recommed...

so what do you think?

**Comment by rvalitov** [comment]
The issue is reopened. Thank you for the investigation and sharing your ideas! I will need to think thoroughly about it.

**Comment by rvalitov** [comment]
My idea is to add a new option to category in ZOO:
![image](https://cloud.githubusercontent.com/assets/16267156/20701018/c49a7214-b621-11e6-8d7a-02af2be9a20b.png)
Then it will be possible to select it in the mapping section of widget:
![image](https://cloud.githubusercontent.com/assets/16267156/20701032/d9166c2a-b621-11e6-9cbd-52a789b017b1.png)

However, such approach lacks flexibility. As far as I know, adding a new field to category in ZOO is a deep modification of ZOO core code, which means that such modifications will be overwritten if the user will try to update the ZOO.

**Comment by marcorensch** [comment]
isn't it possible to solve that by creating a joomla plugin which operates outside of ZOO? 
just an idea so far... :-)

ZOOlanders actually works partial that way (with an additional field from time to time)
