### ISSUE TITLE
Не работает MapEx и Map на одной странице

### ISSUE THREAD

**Issue by edgiru** [rvalitov/widgetkit-map-ex#19]
На странице у меня две карты обычный map и MapEx. Не показывается модуль вообще, т.е. в контенте место для него выделилось, но модуля нет (карта не появилась). Модуль добавил как обычно и стандартный Map (Widgetkit). Создал два маркера. Обыйчный работает, а MapEx нет.

**CMS type**: Joomla or WordPress
Joomla
**CMS version**:
3.4.8
**Version of the widget**:
v1.4.3
**Website URL**:
evrokaskad.ru
**Debug output of the widget**:

**Comment by rvalitov** [comment]
MapEx не работает совместно с другими плагинами, виджетами или модулями, которые тоже используют Google Maps API. Об этом написано [в документации](https://github.com/rvalitov/widgetkit-map-ex/wiki/MapEx-and-other-plugins). Т.е. в Вашей ситуации на одной странице Вы можете использовать либо только Map, либо только MapEx. Вместе их использовать нельзя. Но Вы можете конвертировать Map в MapEx в один клик, если это надо.

**Comment by edgiru** [comment]
Спасибо огромное за Вашу работу!
