### ISSUE TITLE
Центровка карты

### ISSUE THREAD

**Issue by edgiru** [rvalitov/widgetkit-map-ex#21]
На сайте центрую карту, все ок показывает что бы сразу помещались два города. А на мобильном карта остается в том же зуме что и на сайте в итоге мы видим центр карты без точек.
![default](https://cloud.githubusercontent.com/assets/4624056/14050228/8fa2a000-f2cb-11e5-96ce-1fdc9ce46c13.JPG)
![2](https://cloud.githubusercontent.com/assets/4624056/14050229/8fa5a340-f2cb-11e5-9615-231d994dfbb7.JPG)

**CMS type**: Joomla or WordPress
Joomla
**CMS version**:
последняя
**Version of the widget**:
v1.4.3
**Website URL**:

**Debug output of the widget**:

**Comment by rvalitov** [comment]
Как я вижу исходя из скриншотов центр карты на ПК и мобильном устройстве одинаковые (точка в районе Гороховое Поле). Проблема в том, что выбранный Вами масштаб карты (Zoom Level) для ПК смотрится хорошо, а для мобильного устройства это слишком крупный масштаб, поэтому метки не влезают на карту. Эта особенность уже была описана тут #1. Я добавил туда Ваши скриншоты для наглядности. Решения пока нет.

**Comment by rvalitov** [comment]
В релизе 1.4.5 эту функцию я добавил.
