### ISSUE TITLE
Custom unique marker using Zoo content?

### ISSUE THREAD

**Issue by lwlbar** [rvalitov/widgetkit-map-ex#23]
Is it possible to map a custom unique marker from Zoo content (image) instead of widgetkit content?
### System information

**CMS type**: Joomla or WordPress

**CMS version**:

**Version of the widget**:

**Website URL**:

**Debug output of the widget**:

**Comment by rvalitov** [comment]
Hi! 
Does this topic answers your question? https://github.com/rvalitov/widgetkit-map-ex/wiki/Using-MapEx-with-ZOO

If not, then, please, be more specific and describe in details what you need. Thank you.

**Comment by lwlbar** [comment]
Perfect! Thank you Ramil,  nice work :)
