### ISSUE TITLE
Ссылки на маркеры на карте

### ISSUE THREAD

**Issue by edgiru** [rvalitov/widgetkit-map-ex#24]
### System information

**CMS type**: Joomla or WordPress
Joomla
**CMS version**:
последняя
**Version of the widget**:

**Website URL**:

**Debug output of the widget**:

Интересует такой вопрос. Есть ли у маркеров ссылки? т.е. при нажатии на маркер на карте должна быть ссылка (с определенным увеличением карты.) т.е. щелкнули на маркер приблизился маркер масштаб карты увеличилась на определенное расстояние. напишу пример:
к примеру есть много адресов разных магазинов щелкая в отдельном списке на любой магазин или на адрес этого магазина или на логотип сразу переходит на карту которая на этой же странице но отображается ниже списка адресов увеличивается масштаб карты и высвечивается именно маркер этого магазина и уже открытый балун.

**Comment by rvalitov** [comment]
Добрый день. Описанный Вами функционал довольно специфический, поэтому его нет как в оригинальном виджете от Yootheme, так и в моем виджете тоже. Я считаю, что это узконаправленная и слабовостребованная другими пользователями задача, поэтому реализовать я ее в этом виджете не планирую. Технически Ваша задача решается путем создания отдельного виджета на основе стандартного Map или MapEx. Добавляются новые поля в backend виджета, а также пишется новый JavaScript код, который будет реализовывать желаемое поведение виджета при взаимодействии с пользователем. Если Вы желаете, то я могу разработать такой виджет для вас в частном порядке. Если это интересно, то пожалуйста, напишите мне письмо, мой e-mail указан в профиле и мы обсудим детали.
