### ISSUE TITLE
Links in content are not SEO friendly

### ISSUE THREAD

**Issue by lllopo** [rvalitov/widgetkit-map-ex#27]
### Expected behavior

When I put a site link in the content of a place in the regular form of "/index.php?...." and with some SEO activated (JoomSEF in my case), the links should get converted to their SEO friendly url.
### Actual behavior

Actually the links stay in their original form.
### Steps to reproduce the behavior

See 'expected behavior'.

**CMS type**: Joomla

**CMS version**: 3.5.1

**Version of the widget**: 1.4.7

My current fix (and it seems to work ok) is to do JRoute::_($item->escape('link')) on the links output in _content.php

**Comment by rvalitov** [comment]
I've been using Widgetkit with sh404SEF. However at Yootheme support forum the support team suggested to deactivate SEF URLS for Widgetkit component. I will investigate this issue further. Thank you for reporting this!

**Comment by lllopo** [comment]
And it really works for other widgets, without some special treatment. But for Map-ex it does not for some reason. I've needed the 'link' property only, so I haven't tried how it works with links in the 'content' field straight, but for the 'link' - it does not work for sure ... maybe because for google maps it is dynamically added content through javascript and so - it does not pass through the Joomla SEF-ing routines, because fo some ecaping or something.

**Comment by rvalitov** [comment]
Did you also test this with the latest version of standard Map widget?

**Comment by lllopo** [comment]
Nope. Yours is so much better, so I don't use the standard one anywhere.

**Comment by rvalitov** [comment]
Ok :)))

**Comment by rvalitov** [comment]
I confirm this issue. I checked both my widget and the standard widget from latest Widgetkit 2.7.3 with the following SEF components:
- Standard Joomla SEF
- JoomSEF
- sh404SEF

In all cases the URL is not SEF, no matter where the URL is placed: in the content area or in the link field.

I will fix this issue.

**Comment by rvalitov** [comment]
A fix is ready and will be uploaded soon. The manual is updated https://github.com/rvalitov/widgetkit-map-ex/wiki/Support-of-SEF-URLs

@lllopo, I used another approach than you suggested. Because your code is Joomla-specific (is not compatible with Wordpress), besides it doesn't solve the problem with links in _content_ area.

**Comment by lllopo** [comment]
No prob. as far as it is solved, it's fine with me :-).
