### ISSUE TITLE
Maps do not work in UIKit tabs

### ISSUE THREAD

**Issue by lllopo** [rvalitov/widgetkit-map-ex#28]
### Expected behavior

The maps do not get properly rendered, when they are in UIKit tab that is not selected on page load - pins centering does not work at least and this is probably due to wrong size calculations on hidden DOM objects.
### Actual behavior

When the map tab gets rendered, the map does not render on it's right position and also shows some other odd behavior.
### Steps to reproduce the behavior

Put a map widget in an UIKit tab set, in a tab that is not selected by default.
### System information

**CMS type**: Joomla

**CMS version**: 3.5.1

**Version of the widget**:1.4.7

My fix is to add the following in $(document).ready(...) in widget.php :

``` javascript
jQuery(document).on(
    "display.uk.check",
    function(event) {
        var self = jQuery(event.target);
        var map = self.find('[id^="wk-map-ex"]');
        if(map.is(':visible')) {
            map.each(
                function() {
                    var id = jQuery(this).attr('id');
                    var item = getWidgetkitMap(id);
                    if(item) {
                        google.maps.event.trigger(item, "resize");
                        var sub_id = id.substring(9);
                        if(typeof window['updateMap' + sub_id] === 'function') {
                            window['updateMap' + sub_id](item);
                        }
                    }
                }
            );
        }
    }
);
```

**Comment by rvalitov** [comment]
Thank you for reporting this and sharing your code. It seems that it's the same kind of problem as displaying a widget inside a modal. This problem was solved in my widget, [read more](https://github.com/rvalitov/widgetkit-map-ex/wiki/How-to-show-map-in-lightbox). But I didn't test the widget with tabs. I guess it's a similar issue. I will investigate this further and prepare an appropriate fix if necessary.

**Comment by rvalitov** [comment]
I confirm this issue. Tested with Switcher widget with tabs. Will provide a fix for this.

**Comment by rvalitov** [comment]
The fix is ready and the manual is updated https://github.com/rvalitov/widgetkit-map-ex/wiki/Display-MapEx-inside-other-widgets-and-UIKit-components Your code was very helpful! Thank you for sharing!
