### ISSUE TITLE
Option to set Google Maps API key

### ISSUE THREAD

**Issue by lllopo** [rvalitov/widgetkit-map-ex#29]
### Expected behavior

Google Maps API is insisting on adding API key to maps requests recently. Presumingly soon this will become a requirement, having that currently is a warning in the javascript console :

> "Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

So we need an option in the backend of Map-ex to set the API key.

**Version of the widget**: 1.4.7

**Comment by lllopo** [comment]
Sorry, my bad - this is already posted.

**Comment by rvalitov** [comment]
Duplicate of #22
