### ISSUE TITLE
Feature: add translation to languages other than English

### ISSUE THREAD

**Issue by rvalitov** [rvalitov/widgetkit-map-ex#35]
Some translations can be found here https://github.com/yootheme/widgetkit-language
- [x] Core code for multilingual support
- [x] Translation to Russian
- [x] Translation to German

**Comment by marcorensch** [comment]
I can help you and create a german (de-DE) translation if needed?

**Comment by rvalitov** [comment]
Thank you Marco! I will be glad to have your help here:) First of all I will think how to add multilingual support to this widget, so that it won't interfere with original Widgetkit. After that I will post information how to translate and what to translate. Again thank you for volunteering!

**Comment by rvalitov** [comment]
Information about translation of Widgetkit core https://github.com/rvalitov/widgetkit-language

**Comment by rvalitov** [comment]
I created a new plugin for Widgetkit called [FolderEx](https://github.com/rvalitov/widgetkit-folder-ex). It's the first of my plugins for Widgetkit that has multilingual support, more info how to translate the FolderEx is [here](https://github.com/rvalitov/widgetkit-folder-ex/wiki/Translation-issues). This plugin is small and has only a few strings to translate. Besides, 95% of translation for this plugin can be used for MapEx.

Adding multilingual support to MapEx requires to rewrite quite a lot of code. I will do that, and then will provide the similar method to translate the MapEx widget. I will post the related news here.

**Comment by rvalitov** [comment]
Added universal translation rules for all the Widgets and Widgetkits [here](https://github.com/rvalitov/widgetkit-language/wiki/Translation-rules).

Created a project on Transifex to translate MapEx [here](https://www.transifex.com/ramil-valitov/mapex/). 

@marcorensch, I added you into the translation team. 

If someone else is willing to help with translation, it would be very helpful and you are welcome to join the team! Please follow the instructions [here](https://github.com/rvalitov/widgetkit-folder-ex/wiki/Translation-issues) in order to join the translators team.

**Comment by rvalitov** [comment]
A pre-release version of MapEx is available for testing the translations. It can be downloaded from [here](https://github.com/rvalitov/widgetkit-map-ex/releases/tag/v1.5.0.1).

This plugin is shipped with language pack that automatically translates the interface of this plugin into your local language. This translation covers only the interface of this plugin. However, if the original string occurs somewhere else in the Widgetkit (e.g. another plugin or widget), then this string will also be translated automatically.

The pre-release version contains only English and Russian (incomplete translation). Custom translations can be easily applied by copying them into the `languages` folder of the MapEx.

**Comment by rvalitov** [comment]
[Updated widget](https://github.com/rvalitov/widgetkit-map-ex/releases/tag/v1.5.0.2) for testing language translations, some bugs fixed.
