### ISSUE TITLE
Map Type Selection display failure

### ISSUE THREAD

**Issue by marcorensch** [rvalitov/widgetkit-map-ex#36]
### Expected behavior

If i deactivate Styled Map Type and choose 3 other options and Activate the ability for the user to select the map he can change it.
### Actual behavior

The User can change the map type but the selection on the frontside has per default no mapstyle entry.
### Steps to reproduce the behavior

activate the option to choose the map type on the frontend
deactivate the option for the styled Map
### System information

**CMS type**: Joomla

**CMS version**: 3.5.1

**Version of the widget**: 1.5.0.2

**Website URL**: http://inst.nx-designs.ch/

**Debug output of the widget**:
debug mode is still on.
<img width="247" alt="bildschirmfoto 2016-06-24 um 23 18 59" src="https://cloud.githubusercontent.com/assets/11912135/16351030/eb732c36-3a62-11e6-82c9-848726cf9050.png">

**Comment by rvalitov** [comment]
Fixed in last commit for #37
