### ISSUE TITLE
Custom Marker don't show in pre-release version 1.5.1 alpha1

### ISSUE THREAD

**Issue by ProjektOliver** [rvalitov/widgetkit-map-ex#40]
Hi,

when I use customs Markers, there isn`t shown one. When I use debug, it shows:
Fatal error: Call to undefined function url_exists() in ../../com_widgetkit/plugins/widgets/map_ex/views/widget.php on line 79
Here is my link:
http://rappenauer.de/marktplatz/nachrichten/item/tag-der-offenen-tuer.html

all actual versions

**Comment by marcorensch** [comment]
Hi - it looks like there is a problem with the debug function i tested it also on my page with the same result i think rvalitov will fix that shortly :-)
- But first about your issue - can you provide a screen of your marker settings? How "big" (width / height) is the image that you are using?

**Comment by ProjektOliver** [comment]
It´s a PNG with 50x50 pixel
[http://awesomescreenshot.com/0d15ziwx59](url)
[http://awesomescreenshot.com/0585zix394](url)

**Comment by rvalitov** [comment]
Thank you, Oliver, for reporting this! The reason is described in #41 by @marcorensch. I will fix this error shortly.

**Comment by rvalitov** [comment]
You can download the patched version from [here](https://github.com/rvalitov/widgetkit-map-ex/archive/master.zip)

**Comment by ProjektOliver** [comment]
thank you, I have update it. But can`t see why the Markers didn`t shown.

**Comment by rvalitov** [comment]
@ProjektOliver , I'm glad that it works fine now. The pre-release versions of the MapEx have lot of rewritten code and may have some bugs, that's why such versions are called "pre-release". Regarding the current issue, the `url_exists` function became a part of a class, but I forgot to update the code that calls this function. If you want, you can use a [stable release](https://github.com/rvalitov/widgetkit-map-ex/releases/latest) of MapEx.

**Comment by ProjektOliver** [comment]
now I have the Plugin Version v1.5.1alpha1 from your download link, but no changes with the marker :(

**Comment by rvalitov** [comment]
It seems that you didn't update the files correctly. Please, make sure to update `widget.php` in the `map_ex/views/` folder with [this one](https://raw.githubusercontent.com/rvalitov/widgetkit-map-ex/master/map_ex/views/widget.php). If the problem will still exist, then please send me the login and password to access your website's administrator panel privately to my e-mail ramilvalitov@gmail.com

**Comment by ProjektOliver** [comment]
Sorry, I turn off Admin tools now

Von: Ramil Valitov [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. Juni 2016 13:41
An: rvalitov/widgetkit-map-ex <widgetkit-map-ex@noreply.github.com>
Cc: Oliver OM. Münch <oliver.muench@franz-mediaprint.de>; Mention <mention@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-map-ex] Custom Marker didn`t shown (#40)


It seems that you didn't update the files correctly. Please, make sure to update widget.php in the map_ex/views/ folder with this one<https://raw.githubusercontent.com/rvalitov/widgetkit-map-ex/master/map_ex/views/widget.php>. If the problem will still exist, then please send me the login and password to access your website privately to my e-mail ramilvalitov@gmail.com<mailto:ramilvalitov@gmail.com>

**Comment by rvalitov** [comment]
Found the reason of the problem. The bug seems to happen when SEF URLs are enabled.

**Comment by ProjektOliver** [comment]
ok, but  sh404SEF I have off. Also by joomla SEF?

**Comment by rvalitov** [comment]
It's strange. Because I tested the widget on my several websites with SEF-enabled and disabled, and it works fine. I use sh404SEF on some websites, too. I will investigate further why your website behaves in such extraordinary way...

**Comment by rvalitov** [comment]
It wasn't related to SEF :)

**Comment by ProjektOliver** [comment]
Thank you very much, it works. What means It wasn't related to SEF?

**Comment by rvalitov** [comment]
It was related to internal processing of the URLs by the widget. As I said the pre-release version may have some bugs. I still test it.

**Comment by ProjektOliver** [comment]
ah ok, so it isn`t my mistake. Thank you

**Comment by rvalitov** [comment]
It's not your mistake :) You are welcome. If you will experience any other problems, please, post a new issue.
