### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by rvalitov** [rvalitov/widgetkit-map-ex#45]
The current obviously doesn't support translation of the following strings:
## MapEx specific strings
- [x] Enables/disables the appearance of a Rotate control for controlling the orientation of 45&deg; imagery. By default, the control's presence is determined by the presence or absence of 45&deg; imagery for the given map type at the current zoom and location. You cannot make the control appear if no 45&deg; imagery is currently available.
- [x] Cluster Marker Level
- [x] %from% to %to%
- [x] e.g. %example%
- [x] Downloaded information about # items
- [x] Inherit

The following strings are custom fields that unfortunately are not translatable by Widgetkit design:
- Location
- Enter a location
- CUSTOM PIN IMAGE
- CUSTOM PIN ANCHOR X (PX)
- CUSTOM PIN ANCHOR Y (PX)
## General Widgetkit strings

To translate the following general strings that are shared between different widgets, please, follow [this project](https://github.com/rvalitov/widgetkit-language).
- Settings
- Select
- Manage Fields
- Add Item
- Add Media
- Drop files here
- Upload
- Add Folder
- Pick Media
- Save
- Save & Close

**Comment by marcorensch** [comment]
German Translation is done :-)
