### ISSUE TITLE
Autocomplete not working when typing location

### ISSUE THREAD

**Issue by BloomBoy** [rvalitov/widgetkit-map-ex#47]
### Expected behavior

Allow me to start enter an adress and that google suggest adresses matching the input
### Actual behavior

Nothing happens. grey input on the right side of the input stating that: "Field disabled by MapEx widget"
### System information

Plugin version  v1.5.1
Plugin build date   14/07/2016
Widgetkit version   2.7.3
Database version    2.0.0
jQuery version  1.12.4
UIkit version   2.26.2
AngularJS version   1.3.20
PHP version 7.0.8 (fpm-fcgi)

**CMS type**: Joomla or WordPress
Joomla

**CMS version**:

**Version of the widget**:

**Website URL**:

**Debug output of the widget**:

**Comment by rvalitov** [comment]
Attach a screenshot please.

**Comment by BloomBoy** [comment]
My bad, I had issue with API key...

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by BloomBoy** [comment]
Ok, still have the same issue, watch this short video:
https://vimeo.com/174803732

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by rvalitov** [comment]
Thank you for the video. It helps a lot! First of all the disabled field is disabled on purpose because it's not used by MapEx widget, and this field is not related to the autocomplete feature. The warning notices in the console log are not related to your problem, too. Only the error message about missing file should not be there, I'll investigate why it appears in your case. I never tested the widget with PHP7. May be it's the reason of your problem. I suggest you to test the autocomplete feature in the standard Map widget. Does it work there?

**Comment by rvalitov** [comment]
And please, check the error.log file of Apache (PHP), may be there you will find some more warnings or errors that will help to find the reason of this problem.

**Comment by BloomBoy** [comment]
Hi again,

The standard widget also fails. I checked on another old project thats been
working fine and that also failed. I tested with php 5.6 and on other
server with same issue. To me it seems the warnings below are new, havent
seen them before.

Google Maps API warning: NoApiKeys
https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

Could it be that I have some issue with the api key? Or did gogle change
anything?

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by BloomBoy** [comment]
No issues registered in the error logs by the way.

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by rvalitov** [comment]
The MapEx widget uses the UI controls from the standard Map widget. So, if a standard Map widget fails to autocomplete, then the MapEx fails, too (because as I said they use the same input box). There is an issue #30 that was designed to add a new feature: own controls and give more options and freedom for selecting a location, but this issue isn't solved yet.

As far as I understand this issue happens in Safari? Did you try other browsers (Chrome and Firefox are recommended for testing)?

**Comment by BloomBoy** [comment]
I use Chrome.

Ok, I will test to update widgetkit and se if that solves this issue.

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by rvalitov** [comment]
I doubt that updating will help you, because I also tested the MapEx with Widgetkit 2.7.3 and the autocomplete works fine. And does autocomplete work if you just type the location in the Google Maps https://maps.google.com ?

**Comment by rvalitov** [comment]
If it's possible, please, create an account for me to access the Joomla's backend, so that I can investigate this issue and your website in details. Please, send the credentials privately to my e-mail ramilvalitov@gmail.com

**Comment by BloomBoy** [comment]
Yes, https://maps.google.com works as usual.

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by rvalitov** [comment]
Current status of issue: issue is confirmed, it happens both for Map and MapEx widgets. It's not related with PHP7, widgetkit and Joomla version. Investigation is still ongoing.

**Comment by rvalitov** [comment]
The reason was that the Google Places API was not enabled for the domain.
The [Wiki](https://github.com/rvalitov/widgetkit-map-ex/wiki/Enter-Google-Maps-API-Key) updated.

**Comment by blondie63** [comment]
I've done many tests with: chrome 54, joomla 3.6.4, widgetkit 2.8.2 , MapEx 1.5.2 and i've seen these issues:
1. I can use Api Browser Key (restricted by site referring) but not Api Server key (restricted by server IP), why?
2. On Location field i can search an address but i cannot write coordinates ! why ?
<img width="730" alt="widgetkit-bug-location" src="https://cloud.githubusercontent.com/assets/1261851/19896259/f81142b4-a053-11e6-8e25-f86da9228688.png">
3. I set Api Key on Widgetkit options and also in MapEx pluging global setting but the last one sometimes is not saved.. bug ? i also see that this field accept "auto" as value, what means ?

My Api has all geo enabled:
<img width="240" alt="ash-g-api-geo-all" src="https://cloud.githubusercontent.com/assets/1261851/19896258/f8101ff6-a053-11e6-8164-d93e993369db.png">

**Comment by rvalitov** [comment]
Hi, @blondie63 ! I don't see that your question is related with the original topic of this issue. Can you create a new issue that describes your problem, please? This will help to preserve the correct structure of the issues list, when each issue is related to single question or problem. Thank you!
