### ISSUE TITLE
User Map

### ISSUE THREAD

**Issue by ProjektOliver** [rvalitov/widgetkit-map-ex#49]
is it possible to use my own maps? I make some with special areas in google My Maps with pylonen.

**Comment by rvalitov** [comment]
Can you please attach a screenshot (and/or link to Google Maps manual) so that I can better understand what you mean?

**Comment by ProjektOliver** [comment]
https://www.google.com/maps/d/u/0/viewer?mid=1BT1cEaBpK5oQlGlyMT1Uo_yyizg

You must zoom to Bad Rappenau

**Comment by rvalitov** [comment]
I see now what you mean. Currently MapEx doesn't support such overlays, but theoretically it's possible to add such feature. However, in this case, you will need to input the polygon or polyline data into the widget. Do you know how to export such data (such as points or corner coordinates) from the map you have created?

**Comment by ProjektOliver** [comment]
this is my problem: I think my only ways are to get my own mymap map into the widget or I need the coordinates for json export. But I don`t know how to do this. In my map the area is only a fast example.

**Comment by rvalitov** [comment]
Sure, if I add such feature then the main question is the format to choose for the coordinates (simple comma seperated list, or JSON or XML, etc.). So if you know a tool that helps visually draw such elements, then probably this tool also has export option. In this case I can add support for natively importing of this exported data.

**Comment by ProjektOliver** [comment]
Maybe I can do it with this?
http://www.geocodezip.com/blitz-gmap-editor/test5b.html

**Comment by ProjektOliver** [comment]
I think KML will be the best.
