### ISSUE TITLE
Js error: Uncaught ReferenceError: getWidgetkitMap is not defined

### ISSUE THREAD

**Issue by BloomBoy** [rvalitov/widgetkit-map-ex#5]
Installed your extend widgetkit map today on a joomla site. Wehn it loads it throws the following js error: Uncaught ReferenceError: getWidgetkitMap is not defined.

This is the line of code it complains about:
var item=getWidgetkitMap("wk-map-ex56b21550c7f19");

What file should contain the getWidgetkitMap function?

We are using Widgetkit 2.5.3

**Comment by rvalitov** [comment]
That's strange. This function is in the core of the widget. Can you please provide a link to your website?

**Comment by BloomBoy** [comment]
Sure, here's the link: http://sprinklers.bloomis.se/kontakt

The map is using your extension and it shows up just the custom marker
thats missing.

Morgan Gustafsson
Bloom Webb AB
08-559 24 354

**Comment by rvalitov** [comment]
Download and update the patched plugin.php This should solve the issue. Please, let me know about the results.

**Comment by BloomBoy** [comment]
Yes, that fixed the issue, great!
