### ISSUE TITLE
Cutted words in Info Popup (Backend)

### ISSUE THREAD

**Issue by marcorensch** [rvalitov/widgetkit-map-ex#65]
### Expected behavior
text wrapping in german and english do not cut words.

### Actual behavior
In some cases the words are cutted into pieces because of the max width of the help text box

### Steps to reproduce the behavior
do a mouseover on the info circle.

### System information

**CMS type**: Joomla 

**CMS version**: 3.6.5

**Version of the widget**: latest

**Website URL**: beta.nx-designs.ch

**Debug output of the widget**: necessary?
![cutted](https://cloud.githubusercontent.com/assets/11912135/22337647/c632e074-e3e5-11e6-8f70-45bd8b648b10.jpg)

**Comment by rvalitov** [comment]
This bug appeared in latest CSS of UIKit, the same question was posted here https://yootheme.com/support/question/105684 with no official answer. Fix will be available soon.

**Comment by rvalitov** [comment]
Fixed in version 1.5.7.
