### ISSUE TITLE
getWidgetkitMap function to return null

### ISSUE THREAD

**Issue by GordonBreazz** [rvalitov/widgetkit-map-ex#71]
### System information

**CMS type**: WordPress

**CMS version**: 4.9.4
**plugin version**: v1.5.8

Why getWidgetkitMap function to return null?

**Simple code**

```javascript<div id="my_map">[widgetkit id="53" ]</div>
<script>

  var PageLoaded = false;
  //alert('ok');
  window.onload = function() {
    PageLoaded = true;
    console.log('ok');
    var map_id=jQuery('#my_map>div').attr('id');
    console.log(map_id);       
    var map_object = getWidgetkitMap(map_id);
    map_object.setZoom(8);
    console.log(map_id); 
  }
</script>
```

**Comment by rvalitov** [comment]
Thank you for reporting this. I confirm this problem, it seems it appeared in one of the last versions of the widget. I will fix it soon.

**Comment by rvalitov** [comment]
The problem happened, because you called the function too early, when the Google Map object has not been initialized yet because of async script loading. I fixed this problem in v1.5.9 which is available for download. Please, check the manual, it has been updated: 
https://github.com/rvalitov/widgetkit-map-ex/wiki/Working-with-Google-Map-object-(for-Javascript-programmers)

If you will face any other problems, please, let me know.

**Comment by GordonBreazz** [comment]
Thank you very much for your kind help and support. Let me ask you a few questions.

 - How to programmatically access the list of markers without re-creating the markers?  
 - Is there an easy way to filter and search for objects on the map? I mean plug-in features, and not gmap (without accessing the map, the plug-in keeps a list of objects in itself).
 - Is there any way to replace the marker pop-up (InfoWindow object) with  another info panel ? For example, a mix of a map widgit and a switch widgit.  Where the map objects (markers) to bind the tabs switcher.

I'm creating a map similar to this http://www.bibliogorod.ru/libraries.

Thanks in advance for your help.

**Comment by rvalitov** [comment]
The widget provides only a simple method for accessing the internal Google Map object. But I think that it's not enough to achieve your goal. The answer to all your questions is probably "no". Well, actually it may be possible, but will require lots of JavaScript programming and this approach is not efficient. It's better to improve the widget itself with PHP. In this case it's possible to add the functionality you need. 

I'm available as a freelancer, and can make a special version of this widget for you, if needed. I speak Russian, and you can contact me directly by email ramilvalitov@gmail.com in case you're interested in this.

**Comment by GordonBreazz** [comment]
Thanks for the answer.
