### ISSUE TITLE
"Uncaught ReferenceError: mapexGoogleApiKey is not defined" this error stopped another scripts run on site pages

### ISSUE THREAD

**Issue by GordonBreazz** [rvalitov/widgetkit-map-ex#72]
### System information

**CMS type**: WordPress

**CMS version**: 4.9.4
**plugin version**: v1.5.8

Hi. I use mapex in one page on my site. The map is working correctly.   But  mapex in work it generate error message in js console. This is evident on all pages of the site. It make problems, other Jquery scripts on the page do not work. For example this plugin -  https://ru.wordpress.org/plugins/button-visually-impaired/

DevTools trace info

"wk-scripts-633b737c.js?ver=4.9.4:50 Uncaught ReferenceError: mapexGoogleApiKey is not defined
    at o (wk-scripts-633b737c.js?ver=4.9.4:50)
    at HTMLDocument.<anonymous> (wk-scripts-633b737c.js?ver=4.9.4:199)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

**Comment by rvalitov** [comment]
Thank you for reporting this. I will check it. First, please, confirm the following:

1. Do you use the latest MapEx version which is v1.5.9? You specified that you use 1.5.8.
2. Did you obtain and enter the Google Map API key in the settings of the MapEx as described [here](https://github.com/rvalitov/widgetkit-map-ex/wiki/Enter-Google-Maps-API-Key)?

**Comment by rvalitov** [comment]
I double checked the code and don't see how such situation is possible. Can you please provide a link to a page where this problem happens?

**Comment by GordonBreazz** [comment]
I checked  in v1.5.9 the problem gone. Thank you.

**Comment by GordonBreazz** [comment]
I was wrong. For me the problem is still actual.  Possibly it is local incompatibility YooTheme "Sun Template" weather widget script and mapex. I refused to use Mapex. Now I am writing native js implementation gmap widgit. Thanks for the help. Ticket can be closed.
https://hkar.ru/SZf5

**Comment by rvalitov** [comment]
The MapEx should work fine with other scripts. Can you save and paste here the full contents of the script "wk-scripts-633b737c.js?ver=4.9.4:50"? Or give a link to the website? Without seeing the contents, I can do nothing.

**Comment by jelenov** [comment]
Hi, I'm dealing with a similar issue like GordonBreazz - are there any news in this matter? 

There are no errors on the page where the mapex is used, but all the other pages of the site are displaying the same errors as described by GordonBreazz, in my case this

wk-scripts-4d658904.js:50 Uncaught ReferenceError: mapexGoogleApiKey is not defined
    at o (wk-scripts-4d658904.js:50)
    at HTMLDocument.<anonymous> (wk-scripts-4d658904.js:199)
    at i (jquery.min.js?79c67d73863227791aa1df3ba1c49bc9:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?79c67d73863227791aa1df3ba1c49bc9:2)
    at Function.ready (jquery.min.js?79c67d73863227791aa1df3ba1c49bc9:2)
    at HTMLDocument.K (jquery.min.js?79c67d73863227791aa1df3ba1c49bc9:2)

Full content of the script is here https://codeshare.io/aVmKJ3

Any idea? Many thanks in advance, Ivo

**Comment by rvalitov** [comment]
Thank you for providing the code. I will check it and send you a patch soon.

**Comment by jelenov** [comment]
That's perfect...  You rock!

**Comment by rvalitov** [comment]
![image](https://user-images.githubusercontent.com/16267156/37288129-85f4eeba-2617-11e8-9c10-1c334f5e2372.png)

Unfortunately, the Codeshare is down for several hours, and I didn't expect that it can happen, so I didn't download the file. Can you please publish the code again, may be right here?

**Comment by jelenov** [comment]
Oops! Here you are... 
[wk-scripts-4d658904.js.zip](https://github.com/rvalitov/widgetkit-map-ex/files/1803235/wk-scripts-4d658904.js.zip)

**Comment by rvalitov** [comment]
Thank you! Can you also please publish the source HTML code of the web page? My widget should inject some JS code into the body tag, I want to check if that happens.

**Comment by jelenov** [comment]
no additional js code is added, see [view.source.html.zip](https://github.com/rvalitov/widgetkit-map-ex/files/1803862/view.source.html.zip)

**Comment by rvalitov** [comment]
Thank you! I made a patch, please, download the new version from here https://github.com/rvalitov/widgetkit-map-ex/archive/master.zip

Waiting for your feedback!

**Comment by jelenov** [comment]
Sorry for the late reply... It's working in my case!
Many thanks for your great approach

**Comment by rvalitov** [comment]
Thank you for helping me to solve this issue! Now I have officially released the new version 1.6.0 of the widget where this issue is fixed.
