### ISSUE TITLE
Widgetkit 1.3.2 google maps key

### ISSUE THREAD

**Issue by cha-theo** [rvalitov/widgetkit-map-ex#76]
### Actual behavior
I cant find where to add the api key

### System information
Joomla 3.8.8 | Widgetkit 1.3.2
**CMS type**: Joomla

**CMS version**: 3.8.8

**Version of the widget**: 1.3.2 think so

**Website URL**:

**Comment by rvalitov** [comment]
Hi! Are you sure you use Widgetkit 1.3.2? This plugin requires version 2.4 or later.

**Comment by cha-theo** [comment]
Yes, i found how to do it ty :D

**Comment by rvalitov** [comment]
Great! Then this issue can be closed?

**Comment by rvalitov** [comment]
If you still face this problem, please reopen this issue
